language: ruby
rvm:
  - 2.2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
gemfile:
  - gemfiles/rails4_0.gemfile
  - gemfiles/rails4_1.gemfile
  - gemfiles/rails4_2.gemfile
  - gemfiles/rails5_0.gemfile
  - gemfiles/rails5_1.gemfile
  - gemfiles/rails5_2.gemfile
cache: bundler
bundler_args: "--jobs=2"
before_install:
  - gem install bundler --no-document
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
branches:
  only:
    - master
notifications:
  email: false
  slack:
    secure: ZVIAWIIVaTjj1m4CVUtCj8WZH6HlGvkceKIGbyMOYaSDBAF+2veKrfUMfTeiTiQqveV3dXFjfnHSuP6zV3X1qIT2MrFb+MsDF7uKOMY4xUL+4mtk72sZ1jCdgg5LoBtNz/ueDGI6wIR14q1Z+L9JIlgXSiXKZfoSJj6b71JCAKM=
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: 2.6
      env: RUBYOPT="--jit"
    - rvm: ruby-head
      env: RUBYOPT="--jit"
sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=61b7ac90a58416aff0da12650d731dbdae34c38f806601899e9df3f5883bfedc
